version: '3'

services:
  # Database
  db:
    image: mariadb
    volumes:
      - "$MARIADB_VOL_PATH:/var/lib/mysql"
    restart: "no"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - wpsite      
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: "no"
    env_file: .env
    volumes: ['$WORDPRESS_VOL_PATH:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: $MARIADB_DATABASE
      WORDPRESS_DB_USER: $MARIADB_USER
      WORDPRESS_DB_PASSWORD: $MARIADB_PASSWORD
    networks:
      - wpsite      
networks:
  wpsite: